-- liquibase formatted sql
-- changeset ontour:init_db_ontour_sample.sql
-- preconditions onFail:MARK_RAN onError:WARN

--
-- Reset onTour's datas
--
DELETE FROM ontour_user_tour;
DELETE FROM ontour_step;
DELETE FROM ontour_tour;

--
-- Tour ontour-admin (fr)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, wait_for_element, show_progress ) VALUES ( 'ontour-admin', 'fr', 'Découvrir les visites guidées', 'Visite livrée par le plugin onTour : présentation de l''écran de gestion des visites.', 'BO', 'jsp/admin/plugins/ontour/ManageTours.jsp', '', '[data-ontour="ontour-add"]', 'first_visit', 1, 1, 1, 1500, 1);
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 1, '', 'Bienvenue dans onTour', 'Une visite guidée met en évidence, étape par étape, les éléments d''une page du back office ou du front office.', '', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 2, '[data-ontour="ontour-add"]', 'Créer une visite', 'Indiquez la page ciblée (chemin et paramètres) et le mode de démarrage : manuel, à la première visite ou à chaque visite.', 'bottom', 'end', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 3, '#ontour-tour-list', 'Vos visites', 'Chaque visite regroupe des <strong>étapes</strong> : un sélecteur CSS, un titre et un texte (HTML autorisé).', 'top', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 4, '[data-ontour="ontour-steps"]', 'Gérer les étapes', 'Ajoutez, ordonnez et paramétrez les étapes : position de la bulle, boutons, attente d''un élément, etc.', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 5, '[data-ontour="ontour-test"]', 'Tester', 'Ouvre la page ciblée et lance immédiatement la visite (paramètre <code>?ontour=code</code>).', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 6, '[data-ontour="ontour-import"]', 'Importer et exporter', 'Les visites s''échangent au format JSON. Un plugin peut aussi livrer ses visites dans <code>/WEB-INF/plugins/ontour/tours/</code> : elles sont importées au démarrage.', 'bottom', 'end', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 7, '.ontour-launcher-button', 'Relancer une visite', 'Ce bouton liste les visites disponibles sur la page courante.', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'fr';

--
-- Tour ontour-admin (en)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, wait_for_element, show_progress ) VALUES ( 'ontour-admin', 'en', 'Discover the guided tours', 'Tour shipped by the onTour plugin: presentation of the tour management screen.', 'BO', 'jsp/admin/plugins/ontour/ManageTours.jsp', '', '[data-ontour="ontour-add"]', 'first_visit', 1, 1, 1, 1500, 1);
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 1, '', 'Welcome to onTour', 'A guided tour highlights, step by step, the elements of a back office or front office page.', '', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 2, '[data-ontour="ontour-add"]', 'Create a tour', 'Set the target page (path and parameters) and the start mode: manual, on the first visit or on every visit.', 'bottom', 'end', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 3, '#ontour-tour-list', 'Your tours', 'Each tour groups <strong>steps</strong>: a CSS selector, a title and a description (HTML allowed).', 'top', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 4, '[data-ontour="ontour-steps"]', 'Manage the steps', 'Add, order and configure the steps: popover position, buttons, waiting for an element, etc.', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 5, '[data-ontour="ontour-test"]', 'Test', 'Opens the target page and starts the tour right away (<code>?ontour=code</code> parameter).', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 6, '[data-ontour="ontour-import"]', 'Import and export', 'Tours are exchanged as JSON. A plugin can also ship its tours in <code>/WEB-INF/plugins/ontour/tours/</code>: they are imported at startup.', 'bottom', 'end', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 7, '.ontour-launcher-button', 'Start a tour again', 'This button lists the tours available on the current page.', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = 'en';

--
-- Tour ontour-admin (all)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, wait_for_element, show_progress ) VALUES ( 'ontour-admin', '', 'Découvrir les visites guidées', 'Visite livrée par le plugin onTour : présentation de l''écran de gestion des visites.', 'BO', 'jsp/admin/plugins/ontour/ManageTours.jsp', '', '[data-ontour="ontour-add"]', 'first_visit', 1, 0, 1, 1500, 1 );
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 1, '', 'Bienvenue dans onTour', 'Une visite guidée met en évidence, étape par étape, les éléments d''une page du back office ou du front office.', '', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 2, '[data-ontour="ontour-add"]', 'Créer une visite', 'Indiquez la page ciblée (chemin et paramètres) et le mode de démarrage : manuel, à la première visite ou à chaque visite.', 'bottom', 'end', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 3, '#ontour-tour-list', 'Vos visites', 'Chaque visite regroupe des <strong>étapes</strong> : un sélecteur CSS, un titre et un texte (HTML autorisé).', 'top', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 4, '[data-ontour="ontour-steps"]', 'Gérer les étapes', 'Ajoutez, ordonnez et paramétrez les étapes : position de la bulle, boutons, attente d''un élément, etc.', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 5, '[data-ontour="ontour-test"]', 'Tester', 'Ouvre la page ciblée et lance immédiatement la visite (paramètre <code>?ontour=code</code>).', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 6, '[data-ontour="ontour-import"]', 'Importer et exporter', 'Les visites s''échangent au format JSON. Un plugin peut aussi livrer ses visites dans <code>/WEB-INF/plugins/ontour/tours/</code> : elles sont importées au démarrage.', 'bottom', 'end', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align, show_buttons, disable_buttons, show_progress, popover_class, progress_label, next_btn_label, prev_btn_label, done_btn_label, disable_active_interaction, advance_on_click, skip_missing_element, wait_for_element) SELECT id_tour, 7, '.ontour-launcher-button', 'Relancer une visite', 'Ce bouton liste les visites disponibles sur la page courante.', 'left', '', NULL, NULL, -1, '', '', '', '', '', -1, -1, -1, -1 FROM ontour_tour WHERE code = 'ontour-admin' AND lang = '';

--
-- Tour core-admin-home (fr)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, wait_for_element, show_progress ) VALUES ( 'core-admin-home', 'fr', 'Accueil du back office', 'Page d''accueil de l''administration (lutece-core)', 'BO', 'jsp/admin/AdminMenu.jsp', '', '#dashboard-widgets', 'first_visit', 1, 1, 1, 1000, 1 );
INSERT INTO ontour_step ( id_tour, step_order, title, description ) SELECT id_tour, 1, 'Bienvenue dans le back office', 'Cette visite présente l''accueil de l''administration : le menu, le tableau de bord et votre compte.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description ) SELECT id_tour, 2, '#main-menu', 'Le menu', 'Les fonctionnalités sont regroupées par catégorie (contenu, site, applications, système…). Seules celles pour lesquelles vous avez un droit apparaissent.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 3, '#dashboard-widgets', 'Le tableau de bord', 'Chaque plugin peut y afficher un widget : derniers contenus, utilisateurs, tâches à traiter…', 'top' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 4, '#zone-1 .card', 'Un widget', 'Un résumé et des raccourcis vers la fonctionnalité correspondante.', 'right', 'start' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 5, '#dashboard-widgets-tools', 'Personnaliser', 'Réorganisez, repliez ou masquez les widgets. La disposition est mémorisée par votre navigateur.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description ) SELECT id_tour, 6, 'a.nav-link[href="."]', 'Voir le site', 'Ouvre le front office dans un nouvel onglet.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description ) SELECT id_tour, 7, '.user-initials', 'Votre compte', 'Votre nom, votre dernière connexion, vos préférences et la déconnexion.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 8, '.ontour-launcher-button', 'Les visites guidées', 'Ce bouton relance une visite. Il apparaît sur chaque écran qui en propose une.', 'left' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'fr';

--
-- Tour core-admin-home (en)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, wait_for_element, show_progress ) VALUES ( 'core-admin-home', 'en', 'Back office home', 'Administration home page (lutece-core)', 'BO', 'jsp/admin/AdminMenu.jsp', '', '#dashboard-widgets', 'first_visit', 1, 1, 1, 1000, 1 );
INSERT INTO ontour_step ( id_tour, step_order, title, description ) SELECT id_tour, 1, 'Welcome to the back office', 'This tour presents the administration home: the menu, the dashboard and your account.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description ) SELECT id_tour, 2, '#main-menu', 'The menu', 'Features are grouped by category (content, site, applications, system…). Only the ones you have a right for are shown.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 3, '#dashboard-widgets', 'The dashboard', 'Each plugin can show a widget here: latest content, users, tasks to handle…', 'top' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 4, '#zone-1 .card', 'A widget', 'A summary and shortcuts to the matching feature.', 'right', 'start' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 5, '#dashboard-widgets-tools', 'Customize', 'Reorder, collapse or hide the widgets. The layout is remembered by your browser.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description ) SELECT id_tour, 6, 'a.nav-link[href="."]', 'View the site', 'Opens the front office in a new tab.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description ) SELECT id_tour, 7, '.user-initials', 'Your account', 'Your name, your last login, your preferences and logout.' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 8, '.ontour-launcher-button', 'Guided tours', 'This button starts a tour again. It shows on every screen that offers one.', 'left' FROM ontour_tour WHERE code = 'core-admin-home' AND lang = 'en';

--
-- Tour core-manage-users (fr)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, show_progress ) VALUES ( 'core-manage-users', 'fr', 'Gestion des utilisateurs', 'Liste des utilisateurs du back office (lutece-core)', 'BO', 'jsp/admin/user/ManageUsers.jsp', '', '#btn-search-users', 'first_visit', 1, 1, 1, 1 );
INSERT INTO ontour_step ( id_tour, step_order, title, description ) SELECT id_tour, 1, 'Les utilisateurs du back office', 'Cet écran liste les comptes d''administration. Cette visite présente la création, la recherche et les actions sur un compte.' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 2, 'a[href*="CreateUser.jsp"]', 'Ajouter un utilisateur', 'Crée un compte : identité, identifiant de connexion, mot de passe, niveau et groupe de travail.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 3, '#btn-search-users', 'Rechercher', 'Retrouvez un compte par identifiant, nom, prénom, email ou statut (activé, désactivé, anonymisé).', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 4, 'a[href*="ExportUsers.jsp"]', 'Import et export', 'Exporte les comptes, ou en importe depuis un fichier CSV.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 5, 'a[href*="defaultUserParameterValues"]', 'Paramètres avancés', 'Politique de mots de passe, durée de vie des comptes, valeurs par défaut des nouveaux utilisateurs.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 6, '#portlet-type', 'Actions sur un compte', 'Modifier le compte, changer son mot de passe, attribuer ses droits, rôles et groupes de travail, l''anonymiser ou le supprimer.', 'left' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'fr';

--
-- Tour core-manage-users (en)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, show_progress ) VALUES ( 'core-manage-users', 'en', 'User management', 'Back office user list (lutece-core)', 'BO', 'jsp/admin/user/ManageUsers.jsp', '', '#btn-search-users', 'first_visit', 1, 1, 1, 1 );
INSERT INTO ontour_step ( id_tour, step_order, title, description ) SELECT id_tour, 1, 'Back office users', 'This screen lists the administration accounts. This tour presents the creation, the search and the actions on an account.' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 2, 'a[href*="CreateUser.jsp"]', 'Add a user', 'Creates an account: identity, login, password, level and workgroup.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 3, '#btn-search-users', 'Search', 'Find an account by login, last name, first name, email or status (enabled, disabled, anonymized).', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 4, 'a[href*="ExportUsers.jsp"]', 'Import and export', 'Exports the accounts, or imports them from a CSV file.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 5, 'a[href*="defaultUserParameterValues"]', 'Advanced parameters', 'Password policy, account lifetime, default values of the new users.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 6, '#portlet-type', 'Account actions', 'Edit the account, change its password, assign its rights, roles and workgroups, anonymize or delete it.', 'left' FROM ontour_tour WHERE code = 'core-manage-users' AND lang = 'en';

--
-- Tour core-user-rights (fr)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, show_progress ) VALUES ( 'core-user-rights', 'fr', 'Droits d''un utilisateur', 'Attribution des droits d''un utilisateur (lutece-core)', 'BO', 'jsp/admin/user/ModifyUserRights.jsp', '', 'form[action*="DoModifyUserRights"]', 'first_visit', 1, 1, 1, 1 );
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 1, '.card-header-tabs', 'Le compte', 'Ces onglets donnent accès au compte, au mot de passe, aux droits, aux rôles et aux groupes de travail de l''utilisateur.', 'bottom', 'start' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 2, 'input[name="right"]', 'Un droit', 'Chaque droit ouvre une fonctionnalité du back office. Vous ne pouvez attribuer que les droits de votre niveau.', 'right' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 3, '.toggleCheck', 'Tout cocher', 'Sélectionne ou désélectionne tous les droits d''un coup.', 'bottom', 'start' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'fr';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 4, 'form[action*="DoModifyUserRights"] button[type="submit"]', 'Enregistrer', 'Enregistre les droits cochés.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'fr';

--
-- Tour core-user-rights (en)
--
INSERT INTO ontour_tour ( code, lang, title, description, target, page_path, page_parameters, page_selector, trigger_mode, show_launcher, is_enabled, skip_missing_element, show_progress ) VALUES ( 'core-user-rights', 'en', 'User rights', 'Rights assignment of a user (lutece-core)', 'BO', 'jsp/admin/user/ModifyUserRights.jsp', '', 'form[action*="DoModifyUserRights"]', 'first_visit', 1, 1, 1, 1 );
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 1, '.card-header-tabs', 'The account', 'These tabs give access to the account, the password, the rights, the roles and the workgroups of the user.', 'bottom', 'start' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side ) SELECT id_tour, 2, 'input[name="right"]', 'A right', 'Each right opens a back office feature. You can only assign the rights of your own level.', 'right' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 3, '.toggleCheck', 'Select all', 'Selects or clears all the rights at once.', 'bottom', 'start' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'en';
INSERT INTO ontour_step ( id_tour, step_order, element, title, description, side, align ) SELECT id_tour, 4, 'form[action*="DoModifyUserRights"] button[type="submit"]', 'Save', 'Saves the checked rights.', 'bottom', 'end' FROM ontour_tour WHERE code = 'core-user-rights' AND lang = 'en';
